In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt

print(torch.__version__)

2.8.0+cu126


In [ ]:
# 标量
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# 查看维度
scalar.ndim

0

In [ ]:
# 转化为正常 python 对象
scalar.item()

7

In [ ]:
# 向量
vector = torch.tensor([7, 7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# 矩阵
MATRIX = torch.tensor([[1, 2], [4, 5]])
MATRIX

tensor([[1, 2],
        [4, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0, 0:2]

tensor([1, 2])

In [ ]:
# TENSOR 为多个矩阵的集合体

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([2, 2, 3])


In [ ]:
# 创建一个随机向量
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.size()

(tensor([[0.5383, 0.8091, 0.4902, 0.3574],
         [0.5700, 0.7053, 0.6620, 0.6406],
         [0.0872, 0.9313, 0.3553, 0.9724]]),
 torch.Size([3, 4]))

In [ ]:
# 创建全 0 矩阵
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zero_to_ten = torch.arange(0, 10, 2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# 创建相同形状的 tensor
like_tensor = torch.zeros_like(zero_to_ten)
like_tensor

tensor([0, 0, 0, 0, 0])

In [ ]:
# dtypes
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
float_32_tensor.dtype

torch.float32

In [ ]:
# 不建议不同类似的 tensor 进行运算,部分情况下会报错
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16,
    device="cuda",  # 姜shu ju
    requires_grad=False,
)

float_16_tensor.dtype, float_16_tensor.device, float_16_tensor.requires_grad

(torch.float16, device(type='cuda', index=0), False)

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device="cpu")

# 不同设备上的 tensor 不能运算
float_32_tensor * float_16_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
# 修改数据类型
float_32_tensor = float_32_tensor.type(torch.float16)
float_32_tensor.dtype

torch.float16

In [ ]:
a = torch.tensor([1, 2, 3], device="cuda", dtype=torch.float32)
b = torch.tensor([4, 5, 6], device="cuda", dtype=torch.float32)
print(a * b)
print(a @ b)
# torch 内置了矩阵乘法,更快,更强
print(torch.matmul(a, b))

tensor([ 4., 10., 18.], device='cuda:0')
tensor(32., device='cuda:0')
tensor(32., device='cuda:0')


In [ ]:
%%time

print(a @ b)

tensor(32., device='cuda:0')
CPU times: user 2.47 ms, sys: 0 ns, total: 2.47 ms
Wall time: 4.05 ms


In [ ]:
%%time

torch.matmul(a, b)

CPU times: user 726 µs, sys: 0 ns, total: 726 µs
Wall time: 1.33 ms


tensor(32., device='cuda:0')

In [ ]:
torch.arange(0, 9).reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
X = torch.arange(0, 9, dtype=torch.float16).reshape(3, 3)
print(torch.min(X))
print(X.max())
print(torch.mean(X))
print(X.mean())

tensor(0., dtype=torch.float16)
tensor(8., dtype=torch.float16)
tensor(4., dtype=torch.float16)
tensor(4., dtype=torch.float16)


In [ ]:
print(X.argmin())
# 从左到右,从上到下开始计数
print(X.argmax())

tensor(0)
tensor(8)


In [ ]:
x = torch.arange(1, 11)

x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
y = x.reshape(-1, 2)
y

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
# 修改 y,x并不会改变
y[0, 0] = 11
print(y, x, sep="\n**********\n")

tensor([[11,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
**********
tensor([11,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
# 创建视图
z = x.view(-1, 2)
z

tensor([[11,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
z[0, 0] = 11
print(z, x, sep="\n**********\n")

tensor([[11,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
**********
tensor([11,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
x = torch.arange(1, 11)

torch.stack([x, x, x])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
x.shape, torch.stack([x, x, x], dim=1)

(torch.Size([10]),
 tensor([[ 1,  1,  1],
         [ 2,  2,  2],
         [ 3,  3,  3],
         [ 4,  4,  4],
         [ 5,  5,  5],
         [ 6,  6,  6],
         [ 7,  7,  7],
         [ 8,  8,  8],
         [ 9,  9,  9],
         [10, 10, 10]]))

In [ ]:
x = torch.arange(1, 11).reshape(1, 2, 5)
x.shape, x

(torch.Size([1, 2, 5]),
 tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]))

In [ ]:
# 移除维度为1的数据
x_squeezed = torch.squeeze(x)
x_squeezed.shape, x.shape

(torch.Size([2, 5]), torch.Size([1, 2, 5]))

In [ ]:
# 使用 unsqueeze 放大维度
x_orgin = x_squeezed.unsqueeze(dim=0)
x_orgin.shape, x.shape

(torch.Size([1, 2, 5]), torch.Size([1, 2, 5]))

In [ ]:
# try something different
y = x_squeezed.unsqueeze(dim=1)
x_squeezed.shape, y.shape

(torch.Size([2, 5]), torch.Size([2, 1, 5]))

In [ ]:
print(x_squeezed)
print(y)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[[ 1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10]]])


In [ ]:
x = torch.randn(2, 3, 5)
print(x.shape)
# swap axis
y = torch.permute(x, dims=(2, 0, 1))
print(y.shape)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [ ]:
print(x)
print(y)

tensor([[[-0.2179,  0.2184,  0.0801,  1.0421, -0.1557],
         [ 0.8176, -0.8509, -0.4333, -0.6170,  1.2055],
         [-1.0118,  2.0616,  0.6855, -1.2776,  0.7336]],

        [[-1.9147, -0.8426, -0.4719,  0.7551, -0.5982],
         [-0.7071,  1.1983, -0.7110,  0.1047, -1.5245],
         [-1.3155, -0.1940, -0.2133,  1.1999,  0.0509]]])
tensor([[[-0.2179,  0.8176, -1.0118],
         [-1.9147, -0.7071, -1.3155]],

        [[ 0.2184, -0.8509,  2.0616],
         [-0.8426,  1.1983, -0.1940]],

        [[ 0.0801, -0.4333,  0.6855],
         [-0.4719, -0.7110, -0.2133]],

        [[ 1.0421, -0.6170, -1.2776],
         [ 0.7551,  0.1047,  1.1999]],

        [[-0.1557,  1.2055,  0.7336],
         [-0.5982, -1.5245,  0.0509]]])


In [ ]:
# index
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0, :, 2]

tensor([3, 6, 9])

In [ ]:
# numpy & tensor
import numpy as np

a = np.arange(1.0, 11.0).reshape(2, 5)
a.dtype  # 默认类型是 float64

dtype('float64')

In [ ]:
z = torch.tensor([1.0, 2.0, 3.0])
z.dtype  # 默认类型是 float32
# 在进行转化的时候注意由于数据类型不同引发的报错

torch.float32

In [ ]:
# transfer ndarray to tensor and put it to GPU
b = torch.from_numpy(a).to("cuda")
b.device, b.dtype  # 自动适应了 numpy 的数据类型

(device(type='cuda', index=0), torch.float64)

In [ ]:
# transfer ndarray to tensor and change the dtype
print(a.dtype)
# 返回一个副本,之后与 a 完全无关
b = torch.from_numpy(a).type(torch.int32)
b.dtype

int64


torch.int32

In [ ]:
# 将 tensor 转为 ndarray
c = b.numpy()
b.dtype, c.dtype

(torch.int32, dtype('int32'))

In [32]:
import torch

# 设置随机数种子以减少随机性
RANDOM_SEED = 32

# 随机数种子设置之后全局生效(只对CPU而言)
torch.manual_seed(RANDOM_SEED)
a = torch.rand(2, 3)
b = torch.rand(2, 3)

# 创建 GPU 种子
torch.cuda.manual_seed(RANDOM_SEED)
c = torch.rand(2, 3)
d = torch.rand(2, 3)

print(a, b, sep="\n**********\n")
print("\n**********\n")
print(c, d, sep="\n**********\n")

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793]])
**********
tensor([[0.6481, 0.0229, 0.5874],
        [0.3254, 0.9485, 0.5219]])

**********

tensor([[0.8782, 0.7254, 0.6929],
        [0.0259, 0.9319, 0.0913]])
**********
tensor([[0.7177, 0.7271, 0.4967],
        [0.9308, 0.3677, 0.2049]])


In [ ]:
# 检查 cuda 是否可用
torch.cuda.is_available()

True

In [ ]:
import torch

# 适应多种设备的 device 选择
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# 查看可用的 GPU 数量
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])

# move to certain device
tensor_in_gpu = tensor.to(device)
tensor_in_gpu, tensor_in_gpu.device

(tensor([1, 2, 3, 4, 5, 6], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
# numpy 不支持在 GPU 上操作, 需要转到 CPU
numpy_tensor = tensor_in_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# 将其转到 cpu 上并转化为 ndarray
tensor_in_cpu = tensor_in_gpu.cpu().numpy()
tensor_in_cpu, tensor_in_cpu.device

(array([1, 2, 3, 4, 5, 6]), 'cpu')